name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: publish docker hub
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
          image: yongfeili/code-server-with-node
          tags: latest
          registry: docker.io
          dockerfile: ./code-server-with-node/Dockerfile
          directory: ./code-server-with-node/
          username: yongfeili
          password: ${{ secrets.DOCKERHUB_TOKEN }}


